version: '2'

services:
    avahi:
        restart: always
        image: solidnerd/avahi:0.7
        volumes:
            - ./avahi-config:/etc/avahi
        mem_limit: 64m
        network_mode: "host"
